#!/bin/bash
set -e

SERVICE_NAME=$1
NEW_VERSION=$2
PROJECT_PATH=$3

if [ -z "$SERVICE_NAME" ] || [ -z "$NEW_VERSION" ] || [ -z "$PROJECT_PATH" ]; then
    echo "Usage: $0 <service-name> <new-version> <project-path>"
    exit 1
fi

CHANGELOG_FILE="$PROJECT_PATH/CHANGELOG.md"
if [ ! -f "$CHANGELOG_FILE" ]; then
    echo "# Changelog" > "$CHANGELOG_FILE"
    echo "" >> "$CHANGELOG_FILE"
    echo "<!-- Entries below this line are auto-generated by CI/CD pipeline -->" >> "$CHANGELOG_FILE"
fi

DATE=$(date +%Y-%m-%d)

# Get last tag
LAST_TAG=$(git tag -l "$SERVICE_NAME/v*" --sort=-v:refname | head -n 1)

if [ -z "$LAST_TAG" ]; then
    COMMITS=$(git log --pretty=format:"* %s (%h)" -- "$PROJECT_PATH")
else
    COMMITS=$(git log "$LAST_TAG..HEAD" --pretty=format:"* %s (%h)" -- "$PROJECT_PATH")
fi

if [ -z "$COMMITS" ]; then
    echo "No commits found to add to changelog."
    exit 0
fi

FEATS=""
FIXES=""
OTHERS=""

while IFS= read -r commit; do
    if echo "$commit" | grep -qi "\* feat:"; then
        FEATS="${FEATS}${commit}\n"
    elif echo "$commit" | grep -qi "\* fix:"; then
        FIXES="${FIXES}${commit}\n"
    else
        OTHERS="${OTHERS}${commit}\n"
    fi
done <<< "$COMMITS"

NEW_CONTENT="\n## [$NEW_VERSION] - $DATE\n"

if [ ! -z "$FEATS" ]; then
    NEW_CONTENT="${NEW_CONTENT}\n### Added\n${FEATS}"
fi

if [ ! -z "$FIXES" ]; then
    NEW_CONTENT="${NEW_CONTENT}\n### Fixed\n${FIXES}"
fi

if [ ! -z "$OTHERS" ]; then
    NEW_CONTENT="${NEW_CONTENT}\n### Changed\n${OTHERS}"
fi

# Prepend to CHANGELOG.md
MARKER="<!-- Entries below this line are auto-generated by CI/CD pipeline -->"

if grep -q "$MARKER" "$CHANGELOG_FILE"; then
    echo "Adding new entries after marker in $CHANGELOG_FILE"
    # Create a temporary file with the new content
    TMP_FILE=$(mktemp)
    # Use awk to insert content after the marker
    awk -v marker="$MARKER" -v content="$(echo -e "$NEW_CONTENT")" '
        $0 ~ marker { print $0; print content; next }
        { print }
    ' "$CHANGELOG_FILE" > "$TMP_FILE"
    mv "$TMP_FILE" "$CHANGELOG_FILE"
else
    echo "Marker not found, prepending to file"
    echo -e "$NEW_CONTENT\n$(cat "$CHANGELOG_FILE")" > "$CHANGELOG_FILE"
fi

echo "Changelog updated for $NEW_VERSION"
